using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data.OleDb;
using System.Data;

public partial class Customerdetails : System.Web.UI.Page
{
    OleDbConnection con = new OleDbConnection(@"Provider=Microsoft.ACE.OLEDB.12.0;Data Source=C:\Users\HP\Documents\customerdetails.mdb.accdb");
    OleDbCommand cmd = new OleDbCommand();
    OleDbDataReader dr;
    public DataSet ds;
    public OleDbDataAdapter dad;
    protected void Page_Load(object sender, EventArgs e)
    {

    }
    protected void Button2_Click(object sender, EventArgs e)
    {
        cmd.CommandText = "Insert into customerdetails values('" + TextBox1.Text + "','" + DropDownList1.SelectedItem.Value + "','" + DropDownList2.SelectedItem.Value + "','" + DropDownList3.SelectedItem.Value + "','" + DropDownList4.SelectedItem.Value + "','" + DropDownList5.SelectedItem.Value + "','" + Label11.Text + "','" + Label10.Text + "','" + TextBox4.Text + "')";
        cmd.Connection = con;
        con.Open();


        cmd.ExecuteNonQuery();

        con.Close();


        Label12.Text = "Your Order has been placed successfully.";
        Label13.Text = "Thank you for shopping with us !!";

    }
    protected void Button1_Click(object sender, EventArgs e)
    {
        Label11.Text = "";
         Label10.Text = "";
        con = new OleDbConnection(@"Provider=Microsoft.ACE.OLEDB.12.0;Data Source="+Server.MapPath("~/C:/Users/HP/Documents/orderid.mdb.accdb") + "; Persist Security Info=False");
        con.Open();
        String data1;
        data1 = "select * from orderid where orderproductid=" + DropDownList4.SelectedItem.Value;
        dad = new OleDbDataAdapter(data1, con);
        ds = new DataSet();
        dad.Fill(ds);
        if (ds.Tables[0].Rows.Count >= 1)
        {


            Label11.Text = ds.Tables[0].Rows[0]["price"].ToString();
            Label10.Text = ds.Tables[0].Rows[0]["discount"].ToString();
        }  
    }
    protected void Button3_Click(object sender, EventArgs e)
    {
        Label14.Text = "APNA MUSIC PALACE";

        Label15.Text = "Tourist complex, near nehru chowk, Jalgaon";
        Label16.Text = "_____________________________________________________________________________________________";
        Label17.Text = "Full name";
        Label18.Text = "Gender";
        Label19.Text = "Ordertype";
        Label20.Text = "Ordername";
        Label21.Text = "OrderProductID";
        Label22.Text = "Quantity";
        Label23.Text = "Price";
        Label24.Text = "Discount";
        Label25.Text = "Delivery Address";

        Label26.Text = TextBox1.Text;
        Label27.Text = DropDownList1.SelectedItem.Value;
        Label28.Text = DropDownList2.SelectedItem.Value;
        Label29.Text = DropDownList3.SelectedItem.Value;
        Label30.Text = DropDownList4.SelectedItem.Value;
        Label31.Text = DropDownList5.SelectedItem.Value;
        Label32.Text = Label11.Text;
        Label33.Text = Label10.Text;
        Label34.Text = TextBox4.Text;

        Label35.Text = "Invoice bill generated by";
        Label36.Text = "APNA MUSIC PALACE";

    }
    protected void Button6_Click(object sender, EventArgs e)
    {
        Label37.Text = "Fill all the details and click on 'Get price' then click on the 'Place Order' button";
    }
}